export const PRIORITY_STATS_MIN_VIDEOS = 100;
export const PRIORITY_CAPTION_THRESHOLD = 0.10;

export const PRIORITY_CAPTION_WEIGHT = 30;
export const PRIORITY_SUBS_WEIGHT = 10;
export const PRIORITY_DURATION_WEIGHT = 10;
export const PRIORITY_SIMILARITY_WEIGHT = 10;
export const PRIORITY_VIEWS_WEIGHT = 10;

export const PRIORITY_SUBS_CAP = 1_000_000;
export const PRIORITY_DURATION_CAP = 1800;
export const PRIORITY_VIEWS_CAP = 100_000;

export const PRIORITY_BAD_CHANNEL_PENALTY = -150;
export const PRIORITY_MANUAL_BOOST = 500;
