#!/usr/bin/env npx tsx
// Converts a raw YouTube caption JSON (auto-generated or manual) to CaptionSegment[].
// Useful for generating mock data for caption similarity tests.
//
// Usage:
// npx tsx scripts/convert-captions.ts auto-captions.json
// npx tsx scripts/convert-captions.ts manual-captions.json > fixtures/manual.json
// npx tsx scripts/convert-captions.ts auto-captions.json fixtures/auto.json

import { mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname } from "path/win32";

type CaptionSegment = {
  text: string;
  startTime: number;
  endTime: number;
  duration: number;
};

type RawSeg = {
  utf8: string;
  tOffsetMs?: number;
  acAsrConf?: number;
};

type RawEvent = {
  tStartMs: number;
  dDurationMs?: number;
  wWinId?: number;
  aAppend?: number;
  segs?: RawSeg[];
};

type RawCaptionJson = {
  events: RawEvent[];
};

function isAutoGenerated(json: RawCaptionJson): boolean {
  return json.events.some((e) => e.segs?.some((s) => s.acAsrConf !== undefined));
}

function convertManual(json: RawCaptionJson): CaptionSegment[] {
  return json.events
    .filter((e) => e.segs && e.segs.length > 0 && e.dDurationMs !== undefined)
    .map((e) => {
      const text = e.segs!
        .map((s) => s.utf8)
        .join("")
        .replace(/\n/g, " ")
        .trim();
      const duration = e.dDurationMs!;
      return { text, startTime: e.tStartMs, endTime: e.tStartMs + duration, duration };
    })
    .filter((s) => s.text.length > 0);
}

function convertAuto(json: RawCaptionJson): CaptionSegment[] {
  return json.events
    .filter((e) => {
      if (!e.wWinId) return false; // window-definition events have no wWinId
      if (e.aAppend === 1) return false; // newline-scroll markers
      if (!e.segs || e.segs.length === 0) return false;
      if (e.dDurationMs === undefined) return false;
      return true;
    })
    .map((e) => {
      const text = e.segs!
        .map((s) => s.utf8)
        .join("")
        .trim();
      const duration = e.dDurationMs!;
      return { text, startTime: e.tStartMs, endTime: e.tStartMs + duration, duration };
    })
    .filter((s) => s.text.length > 0);
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: npx tsx scripts/convert-captions.ts <input.json> [output.json]");
  process.exit(1);
}

const json = JSON.parse(readFileSync(inputPath, "utf-8")) as RawCaptionJson;
const isAuto = isAutoGenerated(json);
console.error(`Detected: ${isAuto ? "auto-generated" : "manual"} captions`);

const segments = isAuto ? convertAuto(json) : convertManual(json);
console.error(`Converted ${segments.length} segments`);

const output = JSON.stringify(segments, null, 2);

const outputPath = process.argv[3];
if (outputPath) {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, output, "utf-8");
  console.error(`Written to ${outputPath}`);
} else {
  process.stdout.write(output + "\n");
}
